name: "Build Back-End Package"

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      repo-path:
        required: false
        type: string
        default: .
      artifact-name:
        required: true
        type: string
      output-path:
        required: false
        type: string
        default: .

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Setup Node.js version ${{ inputs.node-version }}"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install Dependencies
        shell: bash
        run: |
          pushd './${{ inputs.repo-path }}'
          npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run Build
        shell: bash
        run: |
          pushd './${{ inputs.repo-path }}'
          npm run build

      - name: "Zip build artifact"
        shell: bash
        run: |
          pushd './${{ inputs.repo-path }}/${{ inputs.output-path }}'
          zip -r ${{ inputs.artifact-name }}.zip * 
  
      - name: "Upload Artifact of Function App"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.repo-path }}/${{ inputs.output-path != '.' && inputs.output-path || '' }}/${{ inputs.artifact-name }}.zip
          if-no-files-found: error

      