name: "Deploy Back-End Package"

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
        default: "build-${{ github.event.repository.name }}-${{ github.run_id }}"
      app-name:
        required: true
        type: string
      publish-profile:
        required: true
        type: string
	
    secrets:
      publish-profile:
        required: true
		
    outputs:
      url:
        value: ${{ jobs.build-artifact.output.url }}
	
env:
  ARTIFACT_NAME: ${{ inputs.artifact-name }}
  APP_NAME: ${{ inputs.app-name }}
  PUBLISH_PROFILE_NAME: ${{ secrets.publish-profile }}

jobs:
  build-artifact:
    name: "Azure Functions Deploy"
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deployFunctionApp.outputs.app-url }}
    steps:
      - name: "Download Artifact"
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}

      - name: "Unzip Artifact"
        shell: bash
        run: |
          unzip ${{ env.ARTIFACT_NAME }}.zip -d .
          rm ${{ env.ARTIFACT_NAME}}.zip
        
      - name: "Deploy Function App"
        uses: Azure/functions-action@v1
        id: deployFunctionApp
        with:
          app-name: ${{ env.APP_NAME }}
          package: "."
          publish-profile: ${{ secrets.publish-profile }}