name: "Deploy Front-End Package"

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
        default: "build-${{ github.event.repository.name }}-${{ github.run_id }}"
      environment-name:
        required: false
        type: string
        default: Test
      publish-profile:
        required: true
        type: string
    secrets:
        publish-profile:
          required: true
          
jobs:
  deploy-artifact:
    name: "Web App Deploy"
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment-name}}
      url: ${{ steps.builddeploy.outputs.static_web_app_url }}
    steps:
      - name: "Download Artifact"
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}

      - name: "Unzip Artifact"
        shell: bash
        run: |
          unzip ${{ inputs.artifact-name }}.zip -d .
          rm ${{ inputs.artifact-name }}.zip
        
      - name: "Deploy Azure Web App"
        uses: Azure/functions-action@v1
        id: builddeploy
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          azure_static_web_apps_api_token: ${{ secrets.publish-profile }}
          action: "upload"
          app_location: "/"
          app_artifact_location: "/"
          skip_app_build: true